seed: 1234

trainer:
  overfit_batches: 0.0
  check_val_every_n_epoch: 1
  fast_dev_run: false
  max_epochs: 25
  min_epochs: 1
  num_sanity_val_steps: 0

callbacks:
  model_checkpoint:
    save_top_k: 1
    save_weights_only: true
    mode: "min"
    monitor: "val/loss"
    filename: "{epoch}-{val/loss:.2f}-{val/acc:.2f}"
  early_stopping:
    patience: 3
    mode: "min"
    monitor: "val/loss"
    min_delta: 0.001

data:
  batch_size: 16
  num_workers: 8
  pin_memory: true

lit_model:
  lr: 0.001
  weight_decay: 0.0005
  milestones: [5]
  gamma: 0.1

logger:
  project: "mnist-example"

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
