name: Run Python Examples

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up WANDB_API_KEY
      run: echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV
    - name: Run experiment script
      run: |
        python scripts/run_experiment.py
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
